{{- if .Values.externalSecret.create }}
apiVersion: external-secrets.io/v1beta1
kind: {{ .Values.externalSecret.kind }}
metadata:
  name: {{ include "sftpgo.fullname" . }}
  labels:
    {{- include "sftpgo.labels" . | nindent 4 }}
spec:
  externalSecretName: {{ include "sftpgo.fullname" . }}-external-secret
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: {{ .Values.externalSecret.namespace | default .Release.Namespace }}
  externalSecretSpec:
    refreshInterval: {{ .Values.externalSecret.refreshInterval }}
    secretStoreRef:
      kind: {{ .Values.externalSecret.secretStoreRef.kind }}
      name: {{ .Values.externalSecret.secretStoreRef.name }}
    target:
      name: {{ .Values.externalSecret.target.name }}
      creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
    {{- if .Values.externalSecret.dataFrom }}
    dataFrom:
      {{- toYaml .Values.externalSecret.dataFrom | nindent 6 }}
    {{- end }}
    data:
      {{- range $secretKey, $remoteRefKey := .Values.externalSecret.data }}
      - remoteRef:
          key: {{ $remoteRefKey }}
        secretKey: {{ $secretKey }}
      {{- end }}
{{- end }}
