{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  namespace: {{ .Release.Namespace }}
  name: {{ include "sftpgo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sftpgo.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.persistence.pvc | nindent 2 }}
{{- end }}
